# Generated by Django 4.1.7 on 2023-04-24 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaApp', '0003_rename_nombre_cat_categoria_producto_nombre_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria_producto',
            options={'verbose_name': 'categoriaProd', 'verbose_name_plural': 'categoriasProd'},
        ),
    ]
